# Generated by Django 4.2 on 2023-05-11 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact1',
        ),
    ]
